spring:
  application:
    name: barber-shop-api
  config:
    import: classpath:env.properties
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate